#!/bin/bash
curl -o user_authenticating_into_server <wget https://raw.githubusercontent.com/<thatanoslord>/alx-system_engineering-devops/main/attack_is_the_best_defense/user_authenticating_into_server
>
